### ISSUE TITLE
Questions (and proposal) about inject_file

### ISSUE THREAD

**Issue by dearith** [metwork-framework/acquisition#11]
My use case is as follow:

I want to dispatch "incoming" files into different paths, e.g.  `incoming`, `incoming1 `and `incoming2 `(configured in the config.in of MFDATA) :

```
############################
##### INTERNAL PLUGINS #####
############################
[internal_plugins]
...

# Coma separated list of directory names to watch
# (under ${MFDATA_RUNTIME_HOME}/var/in/)
#
# These directories will be watched by the guess_file_type plugin
# (if [internal_plugins]/install_guess_file_type=1)
# or directly by the switch plugin
# (if [internal_plugins]/install_guess_file_type=0 and
#     [internal_plugins]/install_swich=1)
#
# Note: if [internal_plugins]/install_guess_file_type=0 and
#          [internal_plugins]/install_swich=0, this parameter is useless
watched_directories=incoming,incoming1,incoming2 
...

```

I have 3 plugins foo, foo1, foo2

I want :

- `foo` to process files coming from `incoming` directory
- `foo1` to process files coming from `incoming1` directory
- `foo2` to process files coming from `incoming2` directory

For each plugin, I have a switch rule (among others) to check where the file comes from (with tag `first.core.original_dirname`):
- `foo` process only files whose  `first.core.original_dirname` is `incoming`
- `foo1` process only files whose  `first.core.original_dirname` is `incoming1`
- `foo2` process only files whose  `first.core.original_dirname` is `incoming2`

Currently, `inject_file` with `--incoming` option just uses the first item of the `watched_directories` list (e.g. `incoming`).

So, I can't use it to push my file in the `incoming1` or `incoming2` directory.

I notice we can use `inject_file` with  `--plugin` and `--step` option instead of `--incoming`. So, I could use :

-  `inject_file --plugin foo  --step main my-fileA`
-  `inject_file --plugin foo1  --step main my-fileB`
-  `inject_file --plugin foo2  --step main my-fileC`

But, in this case the `guess_file_type` and `switch` plugins are not "called", and the other switch rules of my plugins are not applied.

Would it be possible to modify `inject_file` to be able to choose the "incoming" directory ?

Is it a good idea to use `inject_file` in a production environment ?

`inject_file` is a good utility to "copy" file, instead of a `cp` command, because with `cp` command and huge files, the file is processed by the plugin before the copy is ended. And then the plugin raises an error because of "bad/incomplete" file. That's why sometimes we use `inject_file` instead of `cp` command. 

I notice if I use `cp` command to copy file and add '.t' extension to the destination filename (the default temp extension in inject_file), the file is not processed until I rename the file by removing the '.t' extension. I did not find in Metwork how this "wonderful" process works. So as a workaround, we can copy (`cp` command) file with '.t' extension in the desired directory (`incoming`, `incoming1` or `incoming2`) and then rename the file to its original name.

**Comment by thefab** [comment]
inject_file is a very small utility (a debug one)

cp /file .../incoming/file.t
mv .../incoming/file.t .../incoming/file

is perfectly ok (and faster than inject_file (because implemented in python, slow to launch if you want to execute thousands of them))

metwork listen for FS events (inotify) but ".t" files are excluded 

when you rename your file without ".t" (in the same directory), this is an atomic operation, so no risk for metwork to read the file (without the ".t" extension) before the renaming is complete

**Comment by dearith** [comment]
@thefab Many thanks for your explanations.

Indeed we noticed that `inject_file` does not work as exepected when there are a lot of files to process.
