### ISSUE TITLE
Question about max_lifetime (data_in) and potential issues with max_lifetime computation.

### ISSUE THREAD

**Issue by dearith** [metwork-framework/acquisition#13]
When failure_policy = keep, if the process fails (retrun False), the input fie is copied in the "trash" directory, with the .tags file.

I realize the files are removed from the "trash" directory after a while.

I found the "lifetime" configuration in the config.ini of the MFDATA module :

```
###################
##### DATA IN #####
###################
[data_in]
# Data preprocessing root (without / at the end)
# dir={{MFMODULE_RUNTIME_HOME}}/var/in

# Max lifetime for a file in trash subdir (in minutes)
# trash_max_lifetime=1440

# Max lifetime for a file in tmp subdir (in minutes)
# tmp_max_lifetime=60

# Max lifetime for a file in data_in_dir but
# not in trash or tmp subdir (in minutes)
# other_max_lifetime=360
```

I understand `trash_max_lifetime `and `tmp_max_lifetime`, but what about `other_max_lifetime` ? Is it linked to failure_policy = move and failure_policy_move_dest_dir ? 

I realize a potential issue with lifetime computation. It seems to be based on the the creation/modifcation time. So, we have to be careful on the way we put the file in the `incoming` directory. Let's assume a file created 24h ago, if I use a `mv `(or `cp -p`) command, the datetime doesn't change, so if my process fails, the file will be copied in the "trash" directory, but if the trash_max_lifetime is 1440 (24h), the file will be deleted almost immediately after the copy.

**Comment by thefab** [comment]
- tmp_max_lifetime is the max lifetime for var/in/tmp files
- trash_max_lifetime is the max lifetime for var/in/trash files
- other_max_lifetime is the max lifetime for var/in files (except those in tmp/trash subdirectories)
