### ISSUE TITLE
Issue (?) when retry_total > 0 : failure_policy is ignored

### ISSUE THREAD

**Issue by dearith** [metwork-framework/acquisition#14]
I experiment the retry configuration with MFDATA plugin and I realize that if retry_total is > 0, the failure_policy is ignored :here is my config.ini :

```
# Number of retry in case of errors (before applying the choosen failure policy)
# 0 => no retry
# x => maximum x retries
retry_total = 5

# The minimum number of seconds (can be a float) to wait before retrying
# (see retry_backoff for details about the algorithm)
retry_min_wait=10

# The maximum number of seconds (can be a float) to wait before retrying
# (see retry_backoff for details about the algorithm)
retry_max_wait=120

# Before each retry, we wait:
# retry_min_wait + retry_backoff * ( 2 ** (retry_attempt_number-1) )
# So with a backoff == 0 (default), we wait exactly retry_min_wait seconds
# before each retry.
# With a backoff == 1, we wait retry_min_wait + 1 seconds for the first retry
#                      we wait retry_min_wait + 2 seconds for the second retry
#                      we wait retry_min_wait + 4 seconds for the third retry
#          [...] note that the waiting time is capped by retry_max_wait
# (retry_backoff can be a float)
retry_backoff=0

# Failure policy : keep (default), delete or move
failure_policy = keep
```

After a 5 retry, my process is still failing. Then, after theses retries, I expected the failure_policy will be applied (here keep) and my input file is copied in hte "trash" directory.

But the file is not copied in the "trash" directory and the file is deleted as mentionned in the step_<plugin_name>_<step_name>_reinject.log file :

```
...
2021-06-01T14:15:50.830804Z     [INFO] (mfdata.foo1.main_reinject#2763919) reinjecting /home/dearith/metwork/mfdata/var/in/step.foo1.main_reinject/b82802fed6f54ab591a5924ba3f002fe into /home/dearith/metwork/mfdata/var/in/step.foo1.main/... attempt 5
2021-06-01T14:15:50.837314Z     [INFO] (mfdata.foo1.main_reinject#2763919) Start the processing of /home/dearith/metwork/mfdata/var/in/step.foo1.main_reinject/b82802fed6f54ab591a5924ba3f002fe...
2021-06-01T14:15:50.838022Z     [INFO] (mfdata.foo1.main_reinject#2763919) End of the /home/dearith/metwork/mfdata/var/in/step.foo1.main_reinject/b82802fed6f54ab591a5924ba3f002fe processing after 0 ms (before_status=False)
2021-06-01T14:15:51.932872Z  [WARNING] (mfdata.foo1.main_reinject#2763919) max retry attempt for /home/dearith/metwork/mfdata/var/in/step.foo1.main_reinject/b82802fed6f54ab591a5924ba3f002fe => deleting
```

Is this the expected behavior ? Are "retry" and failure policy mutually exclusive ? Or is it an issue ?

My use case is as follows :
In a mfdata plugin, I use and need a database to process the input file. For some reasons, il the database is not operational, I can't process the file, but we expected the database is not operational for a "short" time and we want to retry for a period, hoping the database becomes operational "quickly", if this is the case, the file will be processed after n attempts (retry is great !). but if the database is not operational afer the retry_total attempts, I want to be able to recover the input file and then process it again when the database will be OK. But in that case, I definitvely lost my input data file.

**Comment by thefab** [comment]
very interesting question

**Comment by thefab** [comment]
let's have a look at this

**Comment by thefab** [comment]
done in 1.0 and 1.1 releases (mfext and mfdata must be updated)
