### ISSUE TITLE
Proposal : move_step.py using datetime instead time in order to have milliseconds

### ISSUE THREAD

**Issue by dearith** [metwork-framework/acquisition#15]
In `move_step.py` time package is used to get date and time in basename placeholder : 
`time.strftime(tmp)`

time.strftime does not accept milliseconds (%f).

Would it possible to use date time package in order to get milliseconds, e.g.

```
from datetime import datetime
...
datetime.now().strftime(tmp), e.g.  with tmp = '%Y-%m-%d %H:%M:%S.%f'
```

For the Metgate project, the best would be to use utcnow() instead now() :
`datetime.utcnow().strftime(tmp), e.g.  with tmp = '%Y-%m-%d %H:%M:%S.%f'`

**Comment by thefab** [comment]
'sounds as a good idea!

**Comment by thefab** [comment]
But we can't change now() with utcnow() without breaking things for other people

**Comment by dearith** [comment]
Ok for now()

**Comment by thefab** [comment]
done in 1.0 and 1.1 releases (mfext and mfdata must be updated)
